### ISSUE TITLE
Unable to install on macOS 11.5.1 via Homebrew

### ISSUE THREAD

**Issue by NSBum** [wakatara/harsh#14]
**Describe the bug**

Unable to install on macOS 11.5.1 via Homebrew

**To Reproduce**

1. brew install wakatara/tap/harsh

> Make sure your habit and log files are where they should be:

```
~/.config/harsh/habits
~/.config/harsh/log
```

**Expected behavior**

Successful installation.

**Environment (please complete the following information):**

- OS: mac
- OS version: 11.5.1
- Harsh version [harsh --version]

**Additional context**

The following error when installing via Homebrew:

```
==> Installing harsh from wakatara/tap
==> Downloading https://github.com/wakatara/harsh/releases/download/v0.8.10/harsh_Darwin_x86_64.tar.gz
Already downloaded: /Users/alan/Library/Caches/Homebrew/downloads/7273ad51b87cbf5dd695d85f62adcb005edc79ce5aaff9834ac36b7d2595b3eb--harsh_Darwin_x86_64.tar.gz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

Thanks!

**Comment by wakatara** [comment]
Good morning @NSBum  (well, it's early morning here in Singapore, anyway... =] ).

I just upgraded my machine to 10.5.2 this morning, and cannot reproduce your install problem. 

``` 
 λ ~ brew cleanup
 λ ~ brew install harsh
==> Installing harsh from wakatara/tap
==> Downloading https://github.com/wakatara/harsh/releases/download/v0.8.10/harsh_Darwin_x86_64.tar.gz
Already downloaded: /Users/daryl/Library/Caches/Homebrew/downloads/7273ad51b87cbf5dd695d85f62adcb005edc79ce5aaff9834ac36b7d2595b3eb--harsh_Darwin_x86_64.tar.gz
🍺  /usr/local/Cellar/harsh/0.8.10: 5 files, 3.5MB, built in 3 seconds
```

This looks like a possible issue with homebrew though, rather than an issue with harsh.
Can you 
1. upgrade to 10.5.2 OSX (in case it's a weird Big Sur) issue and try again
2. Try to resinstall again with `brew install harsh --verbose`  (it gives a lot more diagnostic info)

and then reply back with the output? My guess is you've got a load path problem in brew somehow - not with harsh, but would need more log info to help you with it. 

lemme know!
Daryl.

**Comment by NSBum** [comment]
Good morning (in Canada, that is... ;-)) Verbose logging didn't really provide anything additional. I ended up installing from the pre-compiled binary for my architecture, rather than chase Homebrew down a rabbit hole; so we're up and running and I'll close the issue.
