### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by audiosupp** [wakatara/harsh#19]
**Describe the bug**

For some reason, recently harsh stop to show log.
harsh log stats works fine as before

**To Reproduce**

Maybe I was track to fast that time when bug occur after.

Error message

```
panic: runtime error: index out of range [-9223372036854775808]

goroutine 1 [running]:
main.buildSpark({0xc0001d6000, 0xc, 0x10}, 0xc00019f6f8?, {0xc0001d6000?, 0xc?, 0x20?}, {0x7e6, 0xa, 0x1d})
	/home/runner/work/harsh/harsh/harsh.go:329 +0x405
main.main.func3(0xc00010d190?)
	/home/runner/work/harsh/harsh/harsh.go:116 +0x1d2
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0001209c0, 0xc000122580)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:495 +0xb3f
github.com/urfave/cli/v2.(*Command).startApp(0xc000174360, 0xc000122580)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x78f
github.com/urfave/cli/v2.(*Command).Run(0x1176d60?, 0xc000128850?)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc000120820, {0x11eeae0?, 0xc0001241e0}, {0xc000128000, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbfd
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
main.main()
	/home/runner/work/harsh/harsh/harsh.go:188 +0x529
```

**Expected behavior**

harsh log shows track graph

**Environment (please complete the following information):**

- OS: mac
- OS version: 11.6.5
- Harsh version 0.8.19

**Additional context**

This is my first time open issue on github, don't be to harsh please :)

**Comment by wakatara** [comment]
Hey @audiosupp !

First off, thanks for using the app! (and the bug report. and you're doing fine using GH, don't worry. =] ).

*Usually* we see this error occurs when there is a difference in the way the habit is written vs the way the entry in the log is written. My _guess_ would be that you either edited you habit file slightly (or accidentally?) or manually altered the log file via the text editor in some way. (another thing to check for since this even caught me once, is if you have an invisible entity in the log file at the end of the line, like a pasted hard return character from vim or similar.

lemme know if that doesn't sort it out after you check. I changed a significant amount of stuff in 0.8.19 so it's possible I goofed something (and surprised `log stats` works if `log` doesn't... 🤔

thanks!
Daryl.
PS> In fact, now I've said all that I'm realizing I should probably wrap this particular error in a better error message, so it lets people know they've hit the problem -- if gthat is in fact the case in this instance. So, looks like you're already improving the app by giving me better error checking ideas... =]

**Comment by audiosupp** [comment]
I don't add new habits, so i dunno if i edited habit file or log somehow.
Anyway I delete log and habits file and start to relog habits with starter habits - now everything works as before. 
When I delete only log file and relog my habits - i still get same error. 
Thx for your help and software!

**Comment by wakatara** [comment]
I actually tried to reproduce the error a few ways between messing with habit and log files. Would you mind terribly providing the habit and log files to me so I can diagnose the issue? It would seem to be with your skipped habits possibly exceeding your scorable habits but that should actually not be possible. =] 
(feel free to scrub the log files if you need to sanitize them a bit before attaching them here.)

Otherwise, I can give you an email to send them to me. 

thanks for helping track down the bug.
D.

**Comment by wakatara** [comment]
(it would be great if you could send them before the sun comes up here in Japan tomorrow, since I'm on a place tomorrow evening, so might have some time to work on this at the airport. thanks!).

**Comment by audiosupp** [comment]
yeah, i don't mind, i send files to your email from your website
that actually maybe possible that i skipped to much of habits, because i stopped loging for couple of days and forget what i do - so i just 's' every habit.

**Comment by wakatara** [comment]
Hey @audiosupp 

Interestingly, on Monterey I cannot reproduce the error with your logfiles even setting the clock back to the day when I think you saw it occur, but I am pretty sure I know what happened. When I try the `harsh log` command with your log files  and my clock set to the last day of your log entries, I get a 
```
Yesterday's Score: NaN%
```

That should *not* happen, and I imagine perhaps on older version of OSX it throws the error (or you compiled with an older version of Go than 1.19 perhaps? Not sure... ).
(I was really puzzled why the error trace was showing an error on the line responsible for calling the score since I had though it was a parsing problem.). 

So, the yesterday's score algo in the denominator takes the scorable habits possible and then subtracts the skipped ones from them. Of course, if you skip them all that causes a divide by zero error and I'm embarrassed I did not even notice that till now.  #facepalm

Since skips are freebies, that should be set to 100% if you skipped everything with legit reasons (since skips are supposed to be unavoidable.). 

Anyhow, thanks for finding this bug! I love it when people help make the software better... =] Sorry if it messed with your experience. I'll be pushing a fix out shortly before I board this big ol plane and that should correct this particular problem. At least, I believe it should.

(so brew update or what have you and you should see an update pending when it's pushed.).

thanks again!
Daryl.

**Comment by wakatara** [comment]
Alrighty... fixed and pushed. You should be able to see 0.8.20 if you are using brew. If you used a compiled binary, the one liner script, or liek doing stuff from scratch. 

(out of curiosity, does your mac use an intel instead of M1 or M2 chip? I am just really amazed I could not reproduce the bug on my M1 chipped Mac even knowing what the problem was.

And thanks once again for reporting the bug and helpnig improve the app!

**Comment by audiosupp** [comment]
Thx you for fixing that bug. I glad I have been helpful!
On Go version: go1.19.2 darwin/amd64
I just recently start to use Go environment. That was actually because of harsh.
Yes, I using brew. So soon, when I get home and stable connection - I defently would update. Thank you again!
I'm using old mbp mid 2014, so yeah, intel
