### ISSUE TITLE
[FEATURE REQUEST] Add command to open harsh config files

### ISSUE THREAD

**Issue by crashmoney** [wakatara/harsh#20]
We're trying to keep harsh as minimal as possible, but...

**Is your feature request related to a problem? Please describe.**
Making a quick change to Harsh configuration files can be inconvenient and clunky. For example, when working in another directory and wanting to make a quick change to harsh – this usually requires changing directories back to `~` home and then a separate command to open the config file in the editor of choice.

**Describe the solution you'd like**
A `harsh config` command that opens config files. It can be split into two commands, like `harsh config log` and `harsh config habits`, to launch the log and habit files respectively.

The preferred editor could be saved as a variable somewhere, or as an argument (either are fine with me).

**Describe alternatives you've considered**
I alias `hcf` in `.zshrc`/`.bashrc` to open the config directory in the editor.

**Additional notes**
Thanks for Harsh! It's a great CLI habit tracker :)

**Comment by wakatara** [comment]
Hmmm... this one may never hit me since I use fish and typing `nvim ...` for me generally autocompletes the history portion for bringing up the harsh config. 

How often do you end up making "quick edits" to the config file though? (genuinely asking.). Harsh is kinda designed so that you `fire and forget` the config changes and touch it very rarely (at least for my use case). I do often edit the log file though if I'm overzealous with the n, y, s or decided I better comment an entry for future me to figure out what was going on.

(and happy new year! Thanks for using harsh!)

**Comment by crashmoney** [comment]
Personally, it's not so much the `habits` config file as much as the `log` file, especially now that my habits are mostly set up. (I imagine that this would be an issue more for people who are still onboarding and going into the config regularly.) The main use case is when, as you said, I click through the `y/n/s` too fast.

My terminal (iTerm2 + zsh) does have a strange issue where sometimes, if I make a typo and attempt to delete, shows me `^H` and various other escape codes. I often just enter that first then go into the config files to clean it up after, thus the need for the alias. I can see how native shell autocompletion could supersede an in-built command, though.

**Comment by crashmoney** [comment]
This may be a separate issue, but I've run into a quirk recently while using harsh where the `harsh log` command runs off the terminal screen (i.e. starts on line 1 and continues into line 2 rather than being one line as shown in screenshots). I'm not sure whether this is an issue on harsh's end, but resizing the window narrower moves the blocks/lines/dots accordingly closer towards the actual habit name. 101 x 37 dimensions seems to get the status for today aligned with the last letter of habits.

(Happy New Year to you too!)

**Comment by wakatara** [comment]
> Personally, it's not so much the `habits` config file as much as the `log` file, especially now that my habits are mostly set up. (I imagine that this would be an issue more for people who are still onboarding and going into the config regularly.) The main use case is when, as you said, I click through the `y/n/s` too fast.

Hehe... well not sure I can do too much about that, though my suggestion was going to be aliasing the config and log file into your shell (like I said, with `fish` 95% of the time mine autocompletes faster than I could write it.

**Comment by wakatara** [comment]
> This may be a separate issue, but I've run into a quirk recently while using harsh where the `harsh log` command runs off the terminal screen (i.e. starts on line 1 and continues into line 2 rather than being one line as shown in screenshots). I'm not sure whether this is an issue on harsh's end, but resizing the window narrower moves the blocks/lines/dots accordingly closer towards the actual habit name. 101 x 37 dimensions seems to get the status for today aligned with the last letter of habits.

There definitely might be a spacing issue if you have your terminal set to lower than say 140 characters across. The consistency/seinfeld graph looks at the last 100 days, there's some pad , and then whatever your habits are, so if your horizontal is set to something smol, you'll probably see some alignment issues.

Note: this is largely because of the fact I have my terminal (kitty) fullscreened and running tmux and tmuxp so I slide on over to it with a keyboard shortcut (C-rightArrow) rather than worrying about it doing side by sides. This is also handy if you use nvim/vim as your code editor btw. Try it! Blog explainer here: 

https://daryl.wakatara.com/a-fistful-of-better-cli-tools/#some-cli-tips

Anyways, I hope you don't hate me, but I'm going to close this without "fixing". While I can certainly see your point on the config file, aliasing to a text editor is easier in the shell and the app is geared towards geeks, sooooo... ¯\\_(ツ)_/¯

Thanks for using the app though! I get jazzed hearing that people are actually using it enough to complain about my design decisions... =]   Hope it is proving super helpful on the 2023 new yer's resolutions!! 

(though now you've said that, I think I'm going to update the README to mention aliasing the config file and log file. I myself have harsh aliased to a simple `h` so end up using `h log` and similar a lot. Thanks for the feedback!)
