### ISSUE TITLE
Add frequency per time period programming for habit completion

### ISSUE THREAD

**Issue by aisneto** [wakatara/harsh#24]
Hello! I believe you've accomplished everything one would expect from a minimalist habit tracker. However, there is a feature that I feel is lacking.

When setting up habits, there should be a way to program them to be completed a specific number of times within a defined period. For example, consider going to the gym. I usually go six times a week, and currently, there is no option to specify this when setting up the habit. While I could choose to skip when the prompt comes up on my off days, dealing with multiple habits with different frequencies per time period (in this case, a week) can become quite convoluted. It would be very helpful to have a tool that automates this check-up for you.

Unfortunately, I do not have the slightest idea of how to implement it, or if it is even doable given the application's original goals and concepts. I just feel that this is the only thing that keeps it from being the best habit tracker I've ever used.

**Comment by wakatara** [comment]
Heya @aisneto !

Aw, thanks for the kind words (and using harsh!). You are, of course, correct... and have noticed the fatal flaw in harsh: it's basically just a counter at present time. When I originally was creating it, I did note even *I* wanted org-mode like non-day divisions like 3/w, 2/month etc etc. (obviously it defaults to "every x days" at the moment.

The key issue here is I need to make the app "calendar-aware" for that, which was complexity I felt might have been overkill to getting it out the door originally. 

But hey, it's 2024 and this is a totally appropriate request, so lemme take a look at over the next few weeks and see if I can punch that out the door. I like the idea myself and hve noted even in my own habits examination that sometimes the day of the week matters greatly, so something I wanted to add into the sparkline and stats anyway. 

Anyhow, thanks for bringing this issue back up. Will cycle back in next week on this one (since in the midst of some large product releases at work atm) and update you.

**Comment by appsplash99** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
DouglasRose, @Floven90, @tekeoglan, @Sts0mrg0, @Eduard197150, @Hurves, @mikirejf, @njbrown, @Metroxe, @alejoasotelo, @hak, @imdeepsharma, @olsanska, @3mp8r3, @adammccnn, @predosoares, @cryptoluxge, @arielvdl, @evertonjovito, @data-miner00

**Comment by wakatara** [comment]
Hey @aisneto !

Sorry to take so long to get back to you. Been a bit busy but managed to move this forward in my spare time (though went down a bad implementation route trying to use the `rrule` library which ended up not working well with the consistency graph approach and just ended up being overcomplex.

Anyhow, `harsh 0.10.0` now supports frequency per time period. So, it is a matter of the target frequecy over a period number of days. For doing something like... hey, I wanna gym 3 times a week, you'd do a 3/7 in your habits file in the place of where you used to do something like a 3 (for every 3 days.). Note: this does a rolling window of 7 days rather than start and ends of weeks, but as noted above, doing hard week, month, and quarter broke the consistency/Seinfeld graph paradigm, so ended up implmenting it (and much more easily) by using a rolling window of days. 

Check it out! I feel I still need to add some sort of sigil on the end of every line where you're sort of mid frequency to indicate progress towards something like 3/7.  (ie. like maybe a  ⅓, ⅔ then full consistency line, but need to think about it a little more and try some things.

Anyhow, I hope you like it and it helps out your habit tracking and getting the things in your life you wanna get done, done.  =] 

ciao !

**Comment by aisneto** [comment]
Thank you for implementing this, Wakatara! I hope to see this project keep growing in the future!
