### ISSUE TITLE
The `harsh log` is quite confusing. (had to post it on here as the 'discussions' link was broken)

### ISSUE THREAD

**Issue by sevennotfound** [wakatara/harsh#29]
![image](https://github.com/user-attachments/assets/b24fef5a-8607-4173-8427-0b5987e9505f)

I have a few questions:
1. What does M W F mean and why is it printed almost randomly on the top?

2. If each line on the right represents an action (y/n/s/blank), why are there 8 lines when I have logs of only a week?
edit: upon checking the logs, I actually had 8 days logged. I was just trying the app out and entered random info. my bad.

3. According to the readme, `harsh log stat` among other commands is supposed to contain color, but mine doesn't show any color even without the `--no-color` flag. I use kitty with fish on fedora if that helps, and other commands like `fastfetch`, for example, do show colors. So I don't think my term is the problem(?)

Also, thank you for taking your time. I loved the app.

**Comment by wakatara** [comment]
Heya @sevennotfound 

First off, thanks for using the app and your kind words. I'm sorry if you found the log command slightly confusing, but let me try to explain (and please suggest how I might update the documentation to make this clearer for folks.).

1. `M W F` stands for Monday Wednesday Friday as the day of the week (admittedly, I should make that slightly less english-cnetric). Feedback from users when the app did not have those markers made it so people found it hard to tell which day referred to which when looking back at their habits and it was an easy add.  =] 
2. Each line represents the consistency chain (the seinfeld graph from left to right) of your habits, so one for each habit. The y/s/n you put in tells the app the outcome on a particular day which either adds to or breaks the graph.
3. Wow, I'm not sure on not seeing the colour of the log stats... you're the first person that's reported not seeing them. I use wezterm myself (on OSX) but do use fish, and def see the colours. I just installed kitty via brew and see the colours again. I'm using a fairly standard and well-tested go lang library for terminal colours which outputs standardANSI escapes ( https://github.com/fatih/color ). `h -n log stats` also turns the colours off in kitty, soooo... perhaps a quirk with how you've set up your terminal colours or such. I know kitty needs an additonal terminfo file from when I used to use it? I am using tmux as well with wezterm and the colours show up fine. Can you let me know if you have your terminal set up for 16, 256 or TrueColor? Might help in terms of diagnosing. Also, are you sure you haven't perhaps aliased harsh -n as I did have someone use some bash alias which messed things up a bit. Lemme know if you can give me some output from your temrinal.

Hope some of that helps sort things out. Quite curious about how you're finding it on fedora since I was thinking of moving my old macbook air over to AsahiLinux at some point which I understand if fedora based (more a debian and arch guy, myself... but... :-) ).

ciao! (and thanks for using the app again.).

**Comment by sevennotfound** [comment]
Hey! Thanks for replying. 
Firstly kitty is set up for 256 colors. And no, I have not aliased `-n` accidentally. Testing it on `gnome-terminal` (which also supports 256 colors) also doesn't show any colors. I've tried running the binary directly as well (i.e no chance of it being aliased) but still no colors pop up.

> M W F stands for Monday Wednesday Friday as the day of the week
I kinda did understood that, but I was wondering why there weren't entries for other days of the week. But I guess that would make it look more cluttered, probably not a good idea lol.

> Each line represents the consistency chain (the seinfeld graph from left to right over time)
I can't seem to find anything on the internet about seinfeld graphs? I wanted to read more about how it worked, but all I found was results related to the tv show.  

> Quite curious about how you're finding it on fedora
- If you're asking about how the app runs on fedora, it's pretty fine, except the colors not showing up problem (idk if it's a fedora problem, though)
- If you're asking in general how I'm dealing with fedora, I'd say it's way simpler and easy to use than archlinux which I used previously. The main reason I even switched to fedora was because I had to format the pc for reasons, and didn't want to go through the headache of setting everything up again. If you're used to using arch, then you'll probably not like how less flexible it is, but it comes with SElinux and all the security things preinstalled, so I didn't have to worry about that. (and privacyguides.org [recommends Fedora](https://www.privacyguides.org/en/desktop/), so yeah)

P.S: you asked about how you would improve the documentation, I think you should explain in a little more detail what each output means (like what you've replied here). Perhaps use ChatGPT to make it more comprehensive? I don't really know how to write documentation so take my view with a grain of salt. :P

Thanks again for your time!

**Comment by sevennotfound** [comment]
Also I have an enhancement idea: A command to mark only a specific habit.
What I mean is instead of having to do `harsh ask` and go through every habit, you should be able to do something like `harsh ask meditation` and be able to set the status for only meditation, for example.

**Comment by wakatara** [comment]
@sevennotfound 

1. Yes, more than M W F looked very cluttered so this was a design decision to clearly indicate but not make things too busy. 
2. The "Seinfeld method" aka consistency graphs is an apocryphal story about getting better at writing jokes, which I think is attributed to Brad Isaac in a (possibly never happened) piece of advice he got from the comedian Jerry Seinfeld. Basically, the idea was had a big year long calendar with a day for every year. Every day he wrote jokes, he put an X down. So, could see how consistent he was being. The idea is turning something into a consistent habit makes you good -- eventually. The original place I saw it (Lifehacker) has killed the original post (largely I think because Seinfeld repudiated it) - but you can see here: https://lifehacker.com/jerry-seinfelds-productivity-secret-281626
3. Lemme play around with toning down my terminals to 256 colours only. Note that both kitty and libvte terminals like gnome terminal support TrueColour so if the default is set to 256, that may be some override you've done in shell or terminal which is messing with the color output (or at least the ansi codes which should be output by the program. I have to admit to not being an expert on ansi terminal escape codes so had punted that to the library, but will play a bit with this. 

Thanks for the suggestions on the documentation. I like them. I'll mention the idea behind the consistency graph aka "seinfeld method" (sad to actually find the story is considered fabricated now), and some greater clarity on how the graphs work. 

I've actually refactored a bunch of code to be a bit more efficient last week (caching results and using `strings.Builder`, so had planned to push that Monday, but will spend a bit of time on the README and incporate those changes shortly. 

If it's ok, I'll keep this Issue open till I have a more definitive answer on testing thinds on TRUECOLOR terminals where they're suppressed down to 256 colours. Can you let me know if you set the downstep in your terminal config or in your shell config? I  will try to reproduce things here. 
(I tried this in osx terminal, wezterm, kitty and alacritty and get colour in each one of them, so suspect this might be a setting you have which I hadn't consdered or something that overrides the go library which sets these... I'd blame Red hat though... =p  

(As for linux distros, personally, I use debian backed with homebrew for more up to date packages. I find this is way more stable than almost every other distro I've used. I tend to shy away from Fedora because of Red Hat's recent changes to upstream changes provision which I think is both OSS and Linux hostile. I've been meaning to bring up a machine with pure alpine linux since I end up using that more than anything these days for containers. But end up keeping on using my old M1 macbook air simply cause I get all the benefits of linux and the hardware is spectacular - part of the reason I keep looking at Asahi which is derived from fedora now.).

**Comment by wakatara** [comment]
> Also I have an enhancement idea: A command to mark only a specific habit. What I mean is instead of having to do `harsh ask` and go through every habit, you should be able to do something like `harsh ask meditation` and be able to set the status for only meditation, for example.

Someone else asked for something quite similar. Not so tricky to implement methinks and keeps things simple without adding another command - kinda works like `h log check {thing}`, so pretty sure I can bash that out in a little while when I get a bit of time.

**Comment by wakatara** [comment]
Documentation done and easily added in the harsh ask fragment function. now changing the log fragment to also work that way.  :-)

**Comment by sevennotfound** [comment]
nice I'm gonna check them out
