### ISSUE TITLE
Sorry! Please choose a valid number (0-7) Error on Windows

### ISSUE THREAD

**Issue by KapilRakh** [wakatara/harsh#4]
**Harsh binary does not work on Windows**

On initial launch when prompted to enter how many days back harsh should start tracking in days, entering any number or carriage return, will return an error "Sorry! Please choose a valid number (0-7)"

**To Reproduce**

1. Launch "harsh.exe ask" on Windows on command line
2. When prompted, enter any number between 0 to 7 or a carriage return

**Expected behavior**

Harsh should accept the input and set up log file.

**Environment**

- OS: Windows
- OS version:Windows 10
- Harsh version 0.8.6

**Actual Behavior**
```
C:\harsh>harsh ask

Your log file looks empty. Let's setup your tracking.

How many days back shall we start tracking from in days?

harsh will ask you about each habit for every day back.

Starting today would be 0. Choose. (0-7) 0

Sorry! Please choose a valid number (0-7) 1

Sorry! Please choose a valid number (0-7) 2
```

**Comment by wakatara** [comment]
Hey Kapil!

Merry Xmas, Kapil !  (if you celebrate)

Sorry, that must have been a bummer after installing. Thank you for reporting the bug.

I may need your help on diagnosing this one if it's *not* what I think because I literally do not have access to a windows machine to bug test (just OSX and Linux). Since I'm looking at the source code right now, I think it's this particularly dumb line I put in @ L503: 

```
dayResult, err := reader.ReadString('\n')
```

which would see a unix or osx return and the number, but not strip a  windows carriage return. I can correct and push this fairly quickly. Are you using brew or similar to get the updates? It should let you know automatically and you can update.

It is after midnight here in Singapore though, so will take a look at it tomorrow and update you.

**Comment by KapilRakh** [comment]
Thank for quickly looking into this. I am using the compiled binaries, not brew.

**Comment by wakatara** [comment]
Hey @KapilRakh 

I used a different Go function to trim the input, so hopefully it is OS safe and removes the extra "\r" that Windows puts into the "\r\n" of line endings (rather than just "\n" in linux and OSX.

You can [download 0.8.7 direct from the releases page](https://github.com/wakatara/harsh/releases/tag/v0.8.7).

Do let me know if you run into any other issues using harsh on Windows. The vast majority of people are using it on OSX or Linux the numbers would indicate.

hope it solves your issues. And thanks for your patience while I try and debug this.
Daryl.
PS> I also need to set up a windows test instance of some description on AWS or something... 😅

**Comment by KapilRakh** [comment]
This has resolved the issue. Windows command prompt does not support certain characters used by the app so UI is not as pretty as it may appear on Mac OS or Linux.  Another issue just popped up is, after running `harsh ask` it shows me dates for last 7 days ending in colon with no prompts and exits. I am going to use the app on Mac OS however more testing is required on Windows before releasing it alongside other OSes.

**Comment by wakatara** [comment]
Can you let me know which characters? As you noted, there was no testing on Windows, but would like to be a bit more OS complete. Figured if demand was there, people would report bugs to help other users and improve it. 

It is very stable on OSX and linux. Been using it for over a year, and pretty happy with it (even vs emacs org-habits.). Enjoy and Happy New Year!

**Comment by KapilRakh** [comment]
1) Enter key: https://github.com/wakatara/harsh/blob/3e7af7b5caf16aeb992d3b9717051376fbc243e6/harsh.go#L181
2) If a habit doesn't have a record but others do, then the spark line shows a ? character (like above). Somehow I managed to not have a record for a habit last week, but other habits have a record.

**Comment by Daryl-DH** [comment]
1. The "⏎" doesn't exist in that form for Windows? Hmmm... I guess I could just use the default but I would have figured the utf-8 entity worked for windows. lemme look into that.
2. Actually, that's intentional to make sure you have not forgotten entries (cause I do that all the time). Gives you the opp to go back and enter something using vim or such... 

Daryl.
