### ISSUE TITLE
[FR] Support habits with quantity

### ISSUE THREAD

**Issue by NightMachinary** [wakatara/harsh#6]
We're trying to keep harsh as minimal as possible, but...

**Is your feature request related to a problem? Please describe.**

E.g., I want to exercise for 45 minutes, study for 6 hours, etc. These are hard to fit into a binary done/undone.

**Describe the solution you'd like**

I like to be able to add a desired quantity to my habits ala https://github.com/codito/habito :
```
$ # add a habit
$ habito add writing 750.0 --units words
You have commited to 750.0 words of writing every day!
```

For plotting, perhaps we can use the height of blocks to indicate how much done each habit is.

**Comment by wakatara** [comment]
Interesting idea. But... are you just wanting to record the amount of stuff you've done into the goal itself tracking wise, because these are decidedly binary - you either wrote 750 words in the day or studied for 6 hours. Do or do not, there is no try. 😝 

I was thinking of a way of possibly handling it as a sparkline graph within the units habit line, but need to try that out to see if it isn't just going to destroy the entire aesthetic. Hmmm... though I am worried it adds an extra level of complexity for little gain if those are supposed to be hard habit goals for you.

**Comment by NightMachinary** [comment]
Thanks. The thing is, these are not supposed to be hard goals for me, and I doubt they are for most people. Any opensource alternative you know of for this purpose?

**Comment by wakatara** [comment]
Hey @NightMachinary 

Off the top of my head, I wrote harsh because I couldn't find anything open source I really liked that worked for me, and I've tried a lot of habit trackers. 

 I want to be super encouraging here because I know how hard it is to start goals, but the fact of the matter is you should focus less on the quantity and more on developing the habit and then ramp up quantity from there. Setting yourself super hard goals at the start will ultimately prove counter-productive to you and you will more than likely give up on them. 

(I'd highly recommend a read of something like James Clear's Atomic Habits to get yourself started with simple, easy habits and then ramp up from there.). Habits and Systems trump goals just about every time. Read my blog post: 

https://daryl.wakatara.com/resolution-keystone-habits-and-foundational-hacks/

For example, on the writing goal, rather than setting your hard 750 words a day, focus on just developing the habit fo writing every day. For example, the writing habit to that amount eluded me for ages until I tweaked one little thing a while back... I started doing Morning Pages. Literally, get up grab coffee, sit down and write... Suddenly I was churning out a couple of pages of stuff every day. Studying 6 hours in a day? I literally set aside my Monday nights as "bowling nights" (an inside joke with friends) and would walk out of the office, order take out, and slam away coding for the entire night till I went to bed to work on my coding skills. So, besides developing the habit, also make sure you have a time and place set aside where you are going to do goals, especially if you want to get to hard ones like this. use your calendar even. 

Anyhow, I think I'm going to decline this feature request because it sort of breaks the simplicity of the tracker which is a key part of its charm and power, i think, but please feel free to fork the code and see if you can build what you need yourself. 

Best of luck with your goals and I hope you manage to crush them. 
ciao!

**Comment by NightMachinary** [comment]
@wakatara Thanks! I developed [my own time tracker](https://github.com/NightMachinary/betterborg/blob/master/stdplugins/timetracker.py) on top of Telegram (which is like an OS for me by now, more so than emacs!), and it solves the quantity issue for me. I have yet to add any habit tracking functionality to it, but it has basic aggregation already done; Here are its records of my last 4 days:
```
Last 4 days, 0:00:00; UNACCOUNTED 2:11
sleep                   1 day, 11:54
sa                      21:12
  .                     16:45
  product evaluation     2:2
  quantified self       1:30
    timetracker         1:30
  development           53
chores                  10:52
  .                     56
  self                  9:56
    study               4:45
    rest                2:3
      .                 16
      eat               1:47
    hygiene             1:24
      bath              1:24
    health              1:19
      brush             1:4
      exercise          15
    sa                  23
study                   9:19
  .                     2:17
  economics             3:58
    finance             3:58
  physics               1:33
    physics 4           1:33
      video             1:33
  cs                    1:30
    ai                  1:30
wasted                  6:47
social                  3:47
  family                2:22
  online                1:24
eat                     2:3
family                  55
nonfiction              51
exercise                48
exploration             36
going out               25
news                    14
```

I'm pretty satisfied with it, especially as I have added some fuzzy matching capabilities and integration with Siri. 

I agree with you, `harsh` is great at what it does, and the proposed feature is too complex.

**Comment by NightMachinary** [comment]
I just added a habit tracking functionality to it as well (this is just a data extraction feature, as the data needed to track the habits were already getting recorded by the time tracker), which allows me to:

* Track counts of activities in given time intervals:
```
chores_self_health_brush

2021-02-14: 0
2021-02-15: 0
2021-02-16: 0
2021-02-17: 0
2021-02-18: 0
2021-02-19: 2
2021-02-20: 2
2021-02-21: 0
```
* Track duration of activities in given time intervals:
```
study

2021-02-14: 0
2021-02-15: 1.02
2021-02-16: 3.59
2021-02-17: 6.34
2021-02-18: 1.51
2021-02-19: 1.09
2021-02-20: 0
2021-02-21: 5.53
```

I am interested in generating (PNG) plots for these data, e.g., in the style of Github contribution chart. Do you know of any libraries that can do this easily?
