### ISSUE TITLE
Add an optional "ask when due" option in config

### ISSUE THREAD

**Issue by joshua-aquino** [wakatara/harsh#9]
We're trying to keep harsh as minimal as possible, but...

**Is your feature request related to a problem? Please describe.**
There are some non-daily habits that I don't want to be asked about until they ought to be done. An example is checking in on relatives. I'd like to do this weekly or biweekly, so I don't need to be asked about it daily. 

Having multiple weekly habits like can slow down the `harsh ask` process.

**Describe the solution you'd like**
Perhaps an option that specifies when harsh asks about a particular habit. The config could have an option like:

```
Check in on parents: 7: 2
Brush teeth: 1
```

In this case, "Check in on parents" should be done every week, but will only be asked about 2 days before it is expected to be done. The option is not specified with "Brush teeth", so it is still asked about daily.

**Describe alternatives you've considered**
I've considered using calcurse and other scheduling programs for such habits, but enjoy the simplicity of having one application for habits and another for general appointments.

**Comment by wakatara** [comment]
Heya @joshua-aquino 

First off, thanks for using the app and contributing back. 

I get what you're trying to get at, but there would be a major downside to what you're asking, so let me explain, as I don't think it solves what you want, but may be a workaround (so, would add this and then a "only flag on ask or habit break thing in the config).

Right now, the "warning" on the when you get a "!" for a habit being due and about to break the chain is somewhat hardcoded. You get asked the day of if weekly, otherwise it's a simple formula for longer times. 

``` go
int(math.Floor(float64(habit.Frequency/7))) + 1
```
Basically, number of weeks of frequency + 1

So, that would not be so difficult to change to a configged number in the habits file and change the warning cadence and then flag those as only being the ones shown.

Here's the rub though... there would be no way for you to enter a habit *before* that date (except by manually inputting it into the log file yourself) if you somehow broke or switched that candence. So, I think most people would think of this enhancement as breaking the app's usability somewhat. 

I do recognize what you're getting at though. In a sense, the fact that the app is a daily logger rather than telling you to review habits weekly or monthly is a bit of a pain. Sometimes you just want to log in that you called your folks weekly (I know since I do this... =] ).

Lemme think a little more on this. I'd describe the problem (reading between the lines) is that we want to move asks from daily to weekly, monthly or an arbitrary period and just asked about them when they get within danger of not being done (unless of course, they have not been done), but I think I need to do a bit of design thinking on how that will work. 

Anyway, thinking of it, though it might need a bit of a think and a change in the way the app works.  I also just handle this by not having so many habits I track in line with the philosophy on habit tracking... =] 

(also, emacs org-habit has a similar feature which might be of interest to you which gives a don't ask before this but definitely ask if not done by this and then a config option to only display things undone or coming up if this is a critical deal breaker for you right now.).

**Comment by joshua-aquino** [comment]
I might look into emacs for these types of habits, and keep harsh for dailies.

Thank you for the response, @wakatara.

**Comment by wakatara** [comment]
@joshua-aquino 

No worries! Thanks for using the app. Sorry I could not accommodate. I am curious how many habits of that sort you have though... I have ab out 18 habits in total and maybe half of them are weekly, monthly, or quarterly, but I set up the input so a simple n <enter> sorts them so I never even notice the ask in the app (and just ctrl-c to break out of the ask loop quite often.).

That works well for me, and I have to say, I built the app *after* using emacs org-habit for a while because of the exact behaviour I mentioned (having to fiddle with the entry.).

Though perhaps I find it a bit therapeutic/cathartic going through the daily list of tasks every day and getting asked if I've done my weekly, monthlies, or quarterlies every day. Keeps it top of mind a bit.

Good luck and thanks for using the app!

**Comment by distbit0** [comment]
maybe a solution here could be to allow marking a single habit as complete, by displaying some kind of unique id/tag string such as a15 next to each habit, so you can then type "harsh ask a15" to have harsh ask only about a15, even if it would have otherwise skipped a15 because a15 is not yet due.

very interested in anyone's thoughts on this approach :)

**Comment by distbit0** [comment]
maybe a solution here could be to allow marking a single habit as complete, by displaying some kind of unique id/tag string such as a15 next to each habit, so you can then type "harsh ask a15" to have harsh ask only about a15, even if it would have otherwise skipped a15 because a15 is not yet due.

very interested in anyone's thoughts on this approach :)

**Comment by wakatara** [comment]
@distbit0 
It's an interesting idea, but with the times / period approach in the renovated system, I don't see how this would work in practice since "due" is no longer just a one off simple days affair if you have something like do it  4 times in 40 days now. Kinda breaks the idea of "consistency/seinfeld" graphs for this... but... 

The `harsh ask ?` where ? is a substring of the habit (much like `harsh log check ?`) might work if we just turned off asking for anything but the due date, though I could see this being more annoying than anything and would need to add a coolean on each habit to support it. 🤔

lemme know what you gus think. I still think I need to understand the need a little better (my worry, is that you both are tracking way too many things... :-) ).

**Comment by distbit0** [comment]
> "due" is no longer just a one off simple days affair if you have something like do it 4 times in 40 days now. Kinda breaks the idea of "consistency/seinfeld" graphs for this... but...

I have noticed this issue is addressed in habit tracking apps like https://github.com/iSoron/uhabits by making a habit due when it needs to be done in order for the "min x times out of every y days" rule to be upheld. I.e. if I have a habit that has a "once per five days rule", and I haven't it done it for four days, then it would be set to "due" today (and also tomorrow if I do not do it today).

> The harsh ask ? where ? is a substring of the habit (much like harsh log check ?) might work if we just turned off asking for anything but the due date, though I could see this being more annoying than anything and would need to add a coolean on each habit to support it. 🤔

What would the boolean be for? Personally I'd find this v useful, as I have ~40 habits, most of which have a frequency of once few days/week/several weeks. :)

**Comment by wakatara** [comment]
@distbit0 @joshua-aquino 
Just wanted to let you guys know I recfactored the harsh ask and log so that you can just have it ask about an individual habit rather than answering everything. 

So, if you had `Pullups: 5/7` in your habit file, using the command `harsh ask pul` would now _only_ ask you about that particular habit and outcome. Not precisely what you guys were asking for, but I believe it has the same effect if the issues was going through the long list of answering the full list of habits with `harsh ask` each time. 

https://github.com/wakatara/harsh/releases/tag/v0.10.6
